# golangci-lint configuration for labours-go
version = 2

[run]
timeout = "5m"
go = "1.23"

[linters]
enable = [
  "errcheck",
  "govet",
  "ineffassign", 
  "staticcheck",
  "unused",
  "gocritic",
  "gosec",
  "misspell",
  "bodyclose",
  "unconvert",
  "unparam",
  "gocyclo",
  "funlen",
  "dupl"
]

[issues]
exclude-use-default = false

# Allow longer functions for CLI commands
[[issues.exclude-rules]]
path = "cmd/.*\\.go"
linters = ["funlen"]

# Allow some complexity in main package
[[issues.exclude-rules]]
path = "main\\.go"
linters = ["gocyclo"]

# Allow unused in test helpers
[[issues.exclude-rules]]
path = ".*_test\\.go"
linters = ["unused", "unparam"]

[linters-settings.goimports]
local-prefixes = "github.com/your-org/labours-go"

[linters-settings.funlen]
lines = 120
statements = 70

[linters-settings.gocyclo]
min-complexity = 15

# Simplified severity configuration
[severity]
default-severity = "error"